# Generated by Django 3.1.5 on 2021-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0003_auto_20210108_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='patient_name',
            new_name='name',
        ),
    ]
