# Generated by Django 3.1.5 on 2021-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0004_auto_20210108_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='name',
            new_name='full_name',
        ),
    ]
