# Generated by Django 3.1.5 on 2021-01-08 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0005_auto_20210108_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
