# Generated by Django 3.1.5 on 2021-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0006_auto_20210108_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
