# Generated by Django 3.1.5 on 2021-01-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0007_auto_20210108_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='registered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
