# Generated by Django 3.1.5 on 2021-01-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0008_auto_20210109_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
