# Generated by Django 3.1.5 on 2021-01-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0009_auto_20210109_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
