# Generated by Django 3.1.5 on 2021-01-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_management', '0010_auto_20210109_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appoint_management.doctors'),
            preserve_default=False,
        ),
    ]
